flipkart_relevant_categories = ['Shirts', 'Skirts', 'Pants', 'Kurtas', 'Jackets', 'Dresses', 'Trousers', 'Kurtis',
                                'Leggings', 'Tunics', 'Tops', 'Coats', 'Shorts', 'Jumpsuits', 'Blazers', 'Cardigans',
                                'Sweaters', 'Sweatshirts', 'Jeans', 'Blouses', 'Salwars', 'Shrugs', 'Stockings',
                                'Shirt', 'Skirt', 'Pant', 'Jacket', 'Dress', 'Trouser',
                                'Legging', 'Tunic', 'Top', 'Coat', 'Short', 'Jumpsuit', 'Blazer', 'Cardigan',
                                'Sweater', 'Sweatshirt', 'Blouse', 'Suits', 'Tights', 'T-Shirt', 'T-Shirts']

flipkart_paperdoll_women = {'Tops': 'top', 'Top': 'top',
                            'Pants': 'pants', 'Pant': 'pants', 'Trousers': 'pants', 'Trouser': 'pants',
                            'Shorts': 'shorts', 'Short': 'shorts',
                            'Jeans': 'jeans',
                            'Jackets': 'jacket', 'Jacket': 'jacket',
                            'Blazers': 'blazer', 'Blazer': 'blazer',
                            'Shirts': 'shirt', 'Shirt': 'shirt',
                            'Skirts': 'skirt', 'Skirt': 'skirt',
                            'Tunics': 'blouse', 'Tunic': 'blouse', 'Blouses': 'blouse', 'Blouse': 'blouse',
                            'Dresses': 'dress', 'Dress': 'dress', 'Kurtis': 'dress', 'Kurtas': 'dress',
                            'Salwars': 'dress',
                            'Sweaters': 'sweater', 'Sweater': 'sweater',
                            'T-Shirts': 't-shirt', 'T-Shirt': 't-shirt',
                            'Cardigans': 'cardigan', 'Cardigan': 'cardigan', 'Shrugs': 'cardigan',
                            'Coats': 'coat', 'Coat': 'coat',
                            'Suits': 'suit', 'Jumpsuits': 'suit', 'Jumpsuit': 'suit',
                            'Leggings': 'tights', 'Tights': 'tights', 'Legging': 'tights',
                            'Sweatshirts': 'sweatshirt', 'Sweatshirt': 'sweater',
                            'Stockings': 'stockings'}