#!/usr/bin/env python

import numpy as np
import pymongo
import argparse
import shutil


# if i run this function on braini2:
# db = constants.db

# if i run this function on brainik80a:
db = pymongo.MongoClient().mydb


dress_sleeve_dict = {
    'strapless': [db.yonatan_dresses.find(
        {'sleeve_length': ['true', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'false']}), np.log(1)],
    'spaghetti_straps': [db.yonatan_dresses.find(
        {'sleeve_length': ['false', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false']}), np.log(2)],
    'regular_straps': [db.yonatan_dresses.find(
        {'sleeve_length': ['false', 'false', 'true', 'false', 'false', 'false', 'false', 'false', 'false']}), np.log(7)],
    'sleeveless': [db.yonatan_dresses.find(
        {'sleeve_length': ['false', 'false', 'false', 'true', 'false', 'false', 'false', 'false', 'false']}), np.log(10)],
    'cap_sleeve': [db.yonatan_dresses.find(
        {'sleeve_length': ['false', 'false', 'false', 'false', 'true', 'false', 'false', 'false', 'false']}), np.log(15)],
    'short_sleeve': [db.yonatan_dresses.find(
        {'sleeve_length': ['false', 'false', 'false', 'false', 'false', 'true', 'false', 'false', 'false']}), np.log(45)],
    'midi_sleeve': [db.yonatan_dresses.find(
        {'sleeve_length': ['false', 'false', 'false', 'false', 'false', 'false', 'true', 'false', 'false']}), np.log(72)],
    'long_sleeve': [db.yonatan_dresses.find(
        {'sleeve_length': ['false', 'false', 'false', 'false', 'false', 'false', 'false', 'true', 'false']}), np.log(100)]
    # 'asymmetry' : [db.yonatan_dresses.find(
    #   {'sleeve_length': ['false', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'true']}), 8]
}

# dress length #
dress_length_dict = {
    'mini_length': [db.yonatan_dresses.find(
        {'dress_length': ['true', 'false', 'false', 'false', 'false', 'false']}), 0],
    'above_knee': [db.yonatan_dresses.find(
        {'dress_length': ['false', 'true', 'false', 'false', 'false', 'false']}), 0],
    'knee_length': [db.yonatan_dresses.find(
        {'dress_length': ['false', 'false', 'true', 'false', 'false', 'false']}), 1],
    'tea_length': [db.yonatan_dresses.find(
        {'dress_length': ['false', 'false', 'false', 'true', 'false', 'false']}), 2],
    'ankle_length': [db.yonatan_dresses.find(
        {'dress_length': ['false', 'false', 'false', 'false', 'true', 'false']}), 3],
    'floor_length': [db.yonatan_dresses.find(
        {'dress_length': ['false', 'false', 'false', 'false', 'false', 'true']}), 3]
}

# men shirt sleeve #
men_shirt_sleeve_dict = {
    'regular_straps': [db.yonatan_men_shirts.find(
        {'shirt_sleeve_length': ['true', 'false', 'false', 'false', 'false']}), 0],
    'sleeveless': [db.yonatan_men_shirts.find(
        {'shirt_sleeve_length': ['false', 'true', 'false', 'false', 'false']}), 1],
    'short_sleeve': [db.yonatan_men_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'true', 'false', 'false']}), 2],
    'midi_sleeve': [db.yonatan_men_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'false', 'true', 'false']}), 3],
    'long_sleeve': [db.yonatan_men_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'false', 'false', 'true']}), 4]
}

# pants length #
pants_length_dict = {
    'bermuda': [db.yonatan_pants.find({'pants_length': ['true', 'false', 'false', 'false']}), 0],
    'knee': [db.yonatan_pants.find({'pants_length': ['false', 'true', 'false', 'false']}), 1],
    'capri': [db.yonatan_pants.find({'pants_length': ['false', 'false', 'true', 'false']}), 2],
    'floor': [db.yonatan_pants.find({'pants_length': ['false', 'false', 'false', 'true']}), 3]
}

# women shirt sleeve #
women_shirt_sleeve_dict = {
    'strapless': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['true', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'false']}), 0],
    'spaghetti_straps': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['false', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false']}), 1],
    'regular_straps': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'true', 'false', 'false', 'false', 'false', 'false', 'false']}), 2],
    'sleeveless': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'false', 'true', 'false', 'false', 'false', 'false', 'false']}), 3],
    'cap_sleeve': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'false', 'false', 'true', 'false', 'false', 'false', 'false']}), 4],
    'short_sleeve': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'false', 'false', 'false', 'true', 'false', 'false', 'false']}), 5],
    'midi_sleeve': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'false', 'false', 'false', 'false', 'true', 'false', 'false']}), 6],
    'long_sleeve': [db.yonatan_women_shirts.find(
        {'shirt_sleeve_length': ['false', 'false', 'false', 'false', 'false', 'false', 'false', 'true', 'false']}), 7]
    # 'asymmetry': [db.yonatan_women_shirts.find(
    #    {'shirt_sleeve_length': ['false', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'true']}), 8]
}

# collar basic #
collar_basic_dict = {
    'crew_neck': 0,
    'scoop_neck': 1,
    'v_neck': 2,
    'deep_v_neck': 3,
    'Henley_t_shirts': 4,
    'polo_collar': 5,
    'tie_neck': 6,
    'turtleneck': 7,
    'Hooded_T_Shirt': 8,
    'strapless': 9
}

# style #
style_dict = {
    'swimsuit': 0,
    'sports': 1,
    'others': 2,
    'prom': 3,
    'bride_dress': 4
}

# deep fashion #
attribute_type_dict = {
    '0': ['a-line', 'shape'],
    '1': ['abstract', 'texture'],
    '2': ['abstract_chevron', 'texture'],
    '3': ['abstract_chevron_print', 'texture'],
    '4': ['abstract_diamond', 'texture'],
    '5': ['abstract_floral', 'texture'],
    '6': ['abstract_floral_print', 'texture'],
    '7': ['abstract_geo', 'texture'],
    '8': ['abstract_geo_print', 'texture'],
    '9': ['abstract_paisley', 'texture'],
    '10': ['abstract_pattern', 'texture'],
    '11': ['abstract_print', 'texture'],
    '12': ['abstract_printed', 'texture'],
    '13': ['abstract_stripe', 'texture'],
    '14': ['acid', 'fabric'],
    '15': ['acid_wash', 'fabric'],
    '16': ['americana', 'style'],
    '17': ['angeles', 'style'],
    '18': ['animal', 'texture'],
    '19': ['animal_print', 'texture'],
    '20': ['ankle', 'shape'],
    '21': ['applique', 'fabric'],
    '22': ['arrow_collar', 'part'],
    '23': ['art', 'style'],
    '24': ['asymmetric', 'shape'],
    '25': ['asymmetrical', 'shape'],
    '26': ['asymmetrical_hem', 'part'],
    '27': ['athletic', 'style'],
    '28': ['audrey', 'style'],
    '29': ['babe', 'style'],
    '30': ['babydoll', 'style'],
    '31': ['back_bow', 'part'],
    '32': ['back_cutout', 'part'],
    '33': ['back_knit', 'part'],
    '34': ['back_lace', 'part'],
    '35': ['back_striped', 'part'],
    '36': ['backless', 'part'],
    '37': ['baja', 'shape'],
    '38': ['bandage', 'shape'],
    '39': ['bandana', 'texture'],
    '40': ['bandana_print', 'texture'],
    '41': ['barbie', 'style'],
    '42': ['baroque', 'texture'],
    '43': ['baroque_print', 'texture'],
    '44': ['baseball', 'style'],
    '45': ['basic', 'style'],
    '46': ['basquiat', 'style'],
    '47': ['batwing', 'part'],
    '48': ['beach', 'style'],
    '49': ['bead', 'fabric'],
    '50': ['beaded', 'fabric'],
    '51': ['beaded_chiffon', 'fabric'],
    '52': ['beaded_collar', 'part'],
    '53': ['beaded_sheer', 'fabric'],
    '54': ['beaded_shift', 'shape'],
    '55': ['beatles', 'style'],
    '56': ['bed', 'style'],
    '57': ['bejeweled', 'fabric'],
    '58': ['bell', 'part'],
    '59': ['bell-sleeve', 'part'],
    '60': ['bella', 'style'],
    '61': ['belted', 'part'],
    '62': ['belted_chiffon', 'part'],
    '63': ['belted_floral', 'part'],
    '64': ['belted_floral_print', 'part'],
    '65': ['belted_lace', 'part'],
    '66': ['belted_maxi', 'part'],
    '67': ['belted_plaid', 'part'],
    '68': ['bermuda', 'shape'],
    '69': ['bib', 'shape'],
    '70': ['big', 'shape'],
    '71': ['bike', 'style'],
    '72': ['biker', 'style'],
    '73': ['bird', 'texture'],
    '74': ['bird_print', 'texture'],
    '75': ['blah', 'style'],
    '76': ['bleach', 'fabric'],
    '77': ['bleached', 'fabric'],
    '78': ['bleached_denim', 'fabric'],
    '79': ['blurred', 'style'],
    '80': ['boat_neck', 'part'],
    '81': ['bodycon', 'shape'],
    '82': ['bodycon_midi', 'shape'],
    '83': ['boho', 'style'],
    '84': ['bold', 'style'],
    '85': ['botanical', 'texture'],
    '86': ['botanical_print', 'texture'],
    '87': ['bow', 'part'],
    '88': ['bow-back', 'part'],
    '89': ['bow-front', 'part'],
    '90': ['box', 'shape'],
    '91': ['box_pleat', 'shape'],
    '92': ['box-pleated', 'shape'],
    '93': ['boxy', 'shape'],
    '94': ['boxy_crop', 'shape'],
    '95': ['boxy_knit', 'shape'],
    '96': ['boxy_lace', 'shape'],
    '97': ['boxy_pocket', 'part'],
    '98': ['boxy_striped', 'texture'],
    '99': ['boyfriend', 'style'],
    '100': ['braided', 'part'],
    '101': ['breton', 'texture'],
    '102': ['breton_stripe', 'texture'],
    '103': ['brocade', 'fabric'],
    '104': ['brooklyn', 'style'],
    '105': ['brooklyn_nets', 'style'],
    '106': ['brushstroke', 'texture'],
    '107': ['brushstroke_print', 'texture'],
    '108': ['burnout', 'fabric'],
    '109': ['bustier', 'shape'],
    '110': ['butterfly', 'texture'],
    '111': ['butterfly_print', 'texture'],
    '112': ['button', 'part'],
    '113': ['button-front', 'part'],
    '114': ['buttoned', 'part'],
    '115': ['cable', 'fabric'],
    '116': ['cable_knit', 'fabric'],
    '117': ['cable-knit', 'fabric'],
    '118': ['caged', 'shape'],
    '119': ['california', 'style'],
    '120': ['camera', 'style'],
    '121': ['cami', 'shape'],
    '122': ['cami_crop', 'shape'],
    '123': ['cami_maxi', 'shape'],
    '124': ['camo', 'texture'],
    '125': ['camouflage', 'texture'],
    '126': ['candy', 'style'],
    '127': ['canvas', 'fabric'],
    '128': ['cap-sleeve', 'part'],
    '129': ['capri', 'shape'],
    '130': ['cardio', 'style'],
    '131': ['cargo', 'shape'],
    '132': ['cat', 'style'],
    '133': ['chambray', 'fabric'],
    '134': ['chambray_drawstring', 'fabric'],
    '135': ['checked', 'texture'],
    '136': ['checkered', 'texture'],
    '137': ['cheetah', 'texture'],
    '138': ['chenille', 'fabric'],
    '139': ['chevron', 'texture'],
    '140': ['chevron_print', 'texture'],
    '141': ['chic', 'style'],
    '142': ['chiffon', 'fabric'],
    '143': ['chiffon_floral', 'texture'],
    '144': ['chiffon_lace', 'fabric'],
    '145': ['chiffon_layered', 'fabric'],
    '146': ['chiffon_maxi', 'shape'],
    '147': ['chiffon_paneled', 'shape'],
    '148': ['chiffon_pleated', 'shape'],
    '149': ['chiffon_shift', 'shape'],
    '150': ['chiffon_shirt', 'fabric'],
    '151': ['chiffon_surplice', 'part'],
    '152': ['chiffon-paneled', 'shape'],
    '153': ['chino', 'fabric'],
    '154': ['chunky', 'fabric'],
    '155': ['chunky_knit', 'fabric'],
    '156': ['cinched', 'part'],
    '157': ['circle', 'texture'],
    '158': ['cities', 'style'],
    '159': ['city', 'style'],
    '160': ['civil', 'style'],
    '161': ['clashist', 'texture'],
    '162': ['classic', 'style'],
    '163': ['classic_cotton', 'fabric'],
    '164': ['classic_crew', 'part'],
    '165': ['classic_crew_neck', 'part'],
    '166': ['classic_denim', 'fabric'],
    '167': ['classic_fit', 'shape'],
    '168': ['classic_knit', 'fabric'],
    '169': ['classic_pocket', 'part'],
    '170': ['classic_skinny', 'shape'],
    '171': ['classic_striped', 'texture'],
    '172': ['classic_v-neck', 'part'],
    '173': ['classic_woven', 'fabric'],
    '174': ['clean', 'fabric'],
    '175': ['clean_wash', 'fabric'],
    '176': ['cloud', 'fabric'],
    '177': ['cloud_wash', 'fabric'],
    '178': ['coast', 'style'],
    '179': ['coated', 'fabric'],
    '180': ['coffee', 'style'],
    '181': ['collar', 'part'],
    '182': ['collar_lace', 'part'],
    '183': ['collared', 'part'],
    '184': ['collarless', 'part'],
    '185': ['collarless_faux', 'part'],
    '186': ['colorblock', 'texture'],
    '187': ['colorblock_pocket', 'part'],
    '188': ['colorblocked', 'texture'],
    '189': ['combo', 'shape'],
    '190': ['combo_maxi', 'shape'],
    '191': ['contrast', 'part'],
    '192': ['contrast_trim', 'part'],
    '193': ['contrast-trimmed', 'part'],
    '194': ['convertible', 'part'],
    '195': ['corduroy', 'fabric'],
    '196': ['cotton', 'fabric'],
    '197': ['cotton_drawstring', 'fabric'],
    '198': ['cotton_knit', 'fabric'],
    '199': ['cotton-blend', 'fabric'],
    '200': ['cover-up', 'shape'],
    '201': ['cowl', 'part'],
    '202': ['cowl_neck', 'part'],
    '203': ['cozy', 'shape'],
    '204': ['crepe', 'fabric'],
    '205': ['crepe_shift', 'shape'],
    '206': ['crepe_woven', 'fabric'],
    '207': ['crew', 'part'],
    '208': ['crew_neck', 'part'],
    '209': ['crinkled', 'fabric'],
    '210': ['crisscross', 'part'],
    '211': ['crisscross-back', 'part'],
    '212': ['crochet', 'fabric'],
    '213': ['crochet_crop', 'shape'],
    '214': ['crochet_embroidered', 'fabric'],
    '215': ['crochet_floral', 'texture'],
    '216': ['crochet_fringe', 'part'],
    '217': ['crochet_knit', 'fabric'],
    '218': ['crochet_lace', 'fabric'],
    '219': ['crochet_maxi', 'shape'],
    '220': ['crochet_mesh', 'fabric'],
    '221': ['crochet_overlay', 'fabric'],
    '222': ['crochet-paneled', 'shape'],
    '223': ['crochet-trimmed', 'part'],
    '224': ['crocheted', 'fabric'],
    '225': ['crocheted_lace', 'fabric'],
    '226': ['crop', 'shape'],
    '227': ['cropped', 'shape'],
    '228': ['cropped_knit', 'shape'],
    '229': ['cross-back', 'part'],
    '230': ['crossback', 'part'],
    '231': ['cuffed', 'part'],
    '232': ['cuffed_denim', 'fabric'],
    '233': ['cuffed-sleeve', 'part'],
    '234': ['curved', 'part'],
    '235': ['curved_hem', 'part'],
    '236': ['cut', 'shape'],
    '237': ['cute', 'style'],
    '238': ['cutoff', 'shape'],
    '239': ['cutout', 'shape'],
    '240': ['cutout_lace', 'fabric'],
    '241': ['cutout_maxi', 'shape'],
    '242': ['cutout_sheath', 'shape'],
    '243': ['cutout-back', 'part'],
    '244': ['dainty', 'style'],
    '245': ['daisy', 'texture'],
    '246': ['daisy_print', 'texture'],
    '247': ['damask', 'fabric'],
    '248': ['daring', 'style'],
    '249': ['dark', 'style'],
    '250': ['darling', 'style'],
    '251': ['deep_v-neck', 'part'],
    '252': ['deep-v', 'part'],
    '253': ['defyant', 'style'],
    '254': ['denim', 'fabric'],
    '255': ['denim_drawstring', 'fabric'],
    '256': ['denim_pencil', 'shape'],
    '257': ['denim_shift', 'shape'],
    '258': ['denim_shirt', 'fabric'],
    '259': ['denim_skater', 'shape'],
    '260': ['denim_utility', 'fabric'],
    '261': ['desert', 'style'],
    '262': ['destroyed', 'style'],
    '263': ['devil', 'style'],
    '264': ['diamond', 'texture'],
    '265': ['diamond_print', 'texture'],
    '266': ['dip-dye', 'fabric'],
    '267': ['dip-dyed', 'fabric'],
    '268': ['distressed', 'fabric'],
    '269': ['distressed_low-rise', 'shape'],
    '270': ['distressed_mid-rise', 'shape'],
    '271': ['distressed_skinny', 'shape'],
    '272': ['ditsy', 'texture'],
    '273': ['ditsy_floral', 'texture'],
    '274': ['ditsy_floral_print', 'texture'],
    '275': ['doll', 'style'],
    '276': ['dolman', 'part'],
    '277': ['dolman_sleeve', 'part'],
    '278': ['dolman-sleeve', 'part'],
    '279': ['dolphin', 'part'],
    '280': ['dolphin_hem', 'part'],
    '281': ['doodle', 'style'],
    '282': ['dot', 'texture'],
    '283': ['dots', 'texture'],
    '284': ['dotted', 'texture'],
    '285': ['double-breasted', 'part'],
    '286': ['drape-front', 'part'],
    '287': ['draped', 'part'],
    '288': ['draped_open-front', 'part'],
    '289': ['draped_shawl', 'part'],
    '290': ['draped_surplice', 'part'],
    '291': ['drapey', 'shape'],
    '292': ['drawstring', 'part'],
    '293': ['dream', 'style'],
    '294': ['dreamcatcher', 'style'],
    '295': ['dreamer', 'style'],
    '296': ['drop_waist', 'part'],
    '297': ['drop-sleeve', 'part'],
    '298': ['drop-waist', 'part'],
    '299': ['dropped', 'part'],
    '300': ['dye', 'fabric'],
    '301': ['dynamite', 'style'],
    '302': ['eagle', 'style'],
    '303': ['edge', 'style'],
    '304': ['eiffel', 'style'],
    '305': ['elasticized', 'fabric'],
    '306': ['elegant', 'style'],
    '307': ['elephant', 'part'],
    '308': ['elephant_print', 'part'],
    '309': ['embellished', 'fabric'],
    '310': ['embroidered', 'fabric'],
    '311': ['embroidered_fit', 'shape'],
    '312': ['embroidered_floral', 'texture'],
    '313': ['embroidered_gauze', 'fabric'],
    '314': ['embroidered_gauze_peasant', 'shape'],
    '315': ['embroidered_lace', 'fabric'],
    '316': ['embroidered_maxi', 'shape'],
    '317': ['embroidered_mesh', 'fabric'],
    '318': ['embroidered_peasant', 'shape'],
    '319': ['embroidered_shift', 'shape'],
    '320': ['embroidered_woven', 'fabric'],
    '321': ['embroidery', 'fabric'],
    '322': ['enchanted', 'style'],
    '323': ['ethereal', 'style'],
    '324': ['everyday', 'style'],
    '325': ['eyelash', 'fabric'],
    '326': ['eyelash_knit', 'fabric'],
    '327': ['eyelash_lace', 'fabric'],
    '328': ['eyelet', 'fabric'],
    '329': ['eyelet_fit', 'shape'],
    '330': ['faded', 'fabric'],
    '331': ['fair', 'fabric'],
    '332': ['fair_isle', 'fabric'],
    '333': ['fan', 'style'],
    '334': ['fancy', 'style'],
    '335': ['faux', 'fabric'],
    '336': ['faux_fur', 'fabric'],
    '337': ['faux_leather', 'fabric'],
    '338': ['faux_leather_mini', 'shape'],
    '339': ['faux_leather_moto', 'shape'],
    '340': ['faux_leather_paneled', 'shape'],
    '341': ['faux_leather_pencil', 'shape'],
    '342': ['faux_leather_skater', 'shape'],
    '343': ['faux_leather_varsity', 'shape'],
    '344': ['faux_leather-paneled', 'shape'],
    '345': ['faux_leather-trimmed', 'part'],
    '346': ['faux_shearling', 'fabric'],
    '347': ['faux_suede', 'fabric'],
    '348': ['faux-wrap', 'shape'],
    '349': ['feather', 'fabric'],
    '350': ['festive', 'style'],
    '351': ['field', 'style'],
    '352': ['fisherman', 'style'],
    '353': ['fit', 'shape'],
    '354': ['fit_flare', 'shape'],
    '355': ['fit_skinny', 'shape'],
    '356': ['fitted', 'shape'],
    '357': ['fitted_v-neck', 'part'],
    '358': ['flare', 'shape'],
    '359': ['flared', 'shape'],
    '360': ['flat', 'part'],
    '361': ['flat_front', 'part'],
    '362': ['flat-front', 'part'],
    '363': ['flawless', 'style'],
    '364': ['flirty', 'style'],
    '365': ['floral', 'texture'],
    '366': ['floral_flutter', 'texture'],
    '367': ['floral_knit', 'fabric'],
    '368': ['floral_lace', 'fabric'],
    '369': ['floral_lace_mini', 'shape'],
    '370': ['floral_lace_sheath', 'shape'],
    '371': ['floral_lace_skater', 'shape'],
    '372': ['floral_maxi', 'shape'],
    '373': ['floral_mesh', 'fabric'],
    '374': ['floral_midi', 'shape'],
    '375': ['floral_mini', 'shape'],
    '376': ['floral_paisley', 'texture'],
    '377': ['floral_pattern', 'texture'],
    '378': ['floral_peasant', 'shape'],
    '379': ['floral_pleated', 'shape'],
    '380': ['floral_print', 'texture'],
    '381': ['floral_print_skater', 'shape'],
    '382': ['floral_print_strapless', 'part'],
    '383': ['floral_print_surplice', 'part'],
    '384': ['floral_shift', 'shape'],
    '385': ['floral_skater', 'shape'],
    '386': ['floral_surplice', 'part'],
    '387': ['floral_textured', 'texture'],
    '388': ['floral-embroidered', 'texture'],
    '389': ['flounce', 'part'],
    '390': ['flounce_maxi', 'shape'],
    '391': ['flounced', 'part'],
    '392': ['flower', 'texture'],
    '393': ['flowy', 'shape'],
    '394': ['floyd', 'style'],
    '395': ['fluted', 'part'],
    '396': ['flutter', 'part'],
    '397': ['flutter_sleeve', 'part'],
    '398': ['flutter-sleeve', 'part'],
    '399': ['foil', 'texture'],
    '400': ['fold-over', 'shape'],
    '401': ['foldover', 'shape'],
    '402': ['folk', 'texture'],
    '403': ['folk_print', 'texture'],
    '404': ['foulard', 'fabric'],
    '405': ['fox', 'style'],
    '406': ['france', 'style'],
    '407': ['frayed', 'fabric'],
    '408': ['free_spirit', 'style'],
    '409': ['french', 'fabric'],
    '410': ['french_terry', 'fabric'],
    '411': ['fresh', 'style'],
    '412': ['frida', 'style'],
    '413': ['fringe', 'part'],
    '414': ['fringed', 'part'],
    '415': ['fur', 'fabric'],
    '416': ['fuzzy', 'fabric'],
    '417': ['fuzzy_knit', 'fabric'],
    '418': ['galaxy', 'style'],
    '419': ['garden', 'style'],
    '420': ['garden_party', 'style'],
    '421': ['gathered_waistline', 'part'],
    '422': ['gaucho', 'shape'],
    '423': ['gauze', 'fabric'],
    '424': ['gauze_maxi', 'shape'],
    '425': ['gauze_peasant', 'shape'],
    '426': ['gauzy', 'fabric'],
    '427': ['gem', 'fabric'],
    '428': ['genuine', 'style'],
    '429': ['geo', 'texture'],
    '430': ['geo_pattern', 'texture'],
    '431': ['geo_print', 'texture'],
    '432': ['geo_stripe', 'texture'],
    '433': ['georgette', 'fabric'],
    '434': ['gingham', 'fabric'],
    '435': ['giraffe', 'texture'],
    '436': ['giraffe_print', 'texture'],
    '437': ['girl', 'style'],
    '438': ['girls', 'style'],
    '439': ['glass', 'fabric'],
    '440': ['glitter', 'fabric'],
    '441': ['graphic', 'texture'],
    '442': ['graphic_muscle', 'shape'],
    '443': ['graphic_racerback', 'part'],
    '444': ['grid', 'texture'],
    '445': ['grid_print', 'texture'],
    '446': ['grunge', 'style'],
    '447': ['guns', 'style'],
    '448': ['halen', 'style'],
    '449': ['harem', 'shape'],
    '450': ['heart', 'texture'],
    '451': ['heart_print', 'texture'],
    '452': ['heat', 'style'],
    '453': ['heathered', 'fabric'],
    '454': ['heathered_knit', 'fabric'],
    '455': ['heathered_stripe', 'texture'],
    '456': ['heathered_v-neck', 'part'],
    '457': ['hem', 'part'],
    '458': ['hepburn', 'style'],
    '459': ['heroes', 'style'],
    '460': ['herringbone', 'fabric'],
    '461': ['high-low', 'shape'],
    '462': ['high-neck', 'part'],
    '463': ['high-rise', 'shape'],
    '464': ['high-rise_skinny', 'shape'],
    '465': ['high-slit', 'part'],
    '466': ['high-slit_maxi', 'part'],
    '467': ['high-waist', 'part'],
    '468': ['high-waisted', 'part'],
    '469': ['hood', 'part'],
    '470': ['hooded', 'part'],
    '471': ['hooded_maxi', 'part'],
    '472': ['hooded_utility', 'part'],
    '473': ['houndstooth', 'texture'],
    '474': ['ikat', 'texture'],
    '475': ['ikat_print', 'texture'],
    '476': ['illusion', 'part'],
    '477': ['illusion_neckline', 'part'],
    '478': ['inset', 'style'],
    '479': ['internet', 'style'],
    '480': ['island', 'style'],
    '481': ['isle', 'style'],
    '482': ['jacquard', 'fabric'],
    '483': ['joie', 'style'],
    '484': ['kahlo', 'style'],
    '485': ['kaleidoscope', 'texture'],
    '486': ['kaleidoscope_print', 'texture'],
    '487': ['kangaroo', 'part'],
    '488': ['kangaroo_pocket', 'part'],
    '489': ['keyhole', 'part'],
    '490': ['kid', 'style'],
    '491': ['killin', 'style'],
    '492': ['kiss', 'style'],
    '493': ['kitty', 'style'],
    '494': ['knee-length', 'shape'],
    '495': ['knit', 'fabric'],
    '496': ['knit_lace', 'fabric'],
    '497': ['knit_longline', 'shape'],
    '498': ['knit_maxi', 'shape'],
    '499': ['knit_mini', 'shape'],
    '500': ['knit_open', 'part'],
    '501': ['knit_pencil', 'shape'],
    '502': ['knit_pocket', 'part'],
    '503': ['knit_raglan', 'part'],
    '504': ['knit_shawl', 'part'],
    '505': ['knit_skater', 'shape'],
    '506': ['knit_stripe', 'texture'],
    '507': ['knit_striped', 'texture'],
    '508': ['knit_trapeze', 'shape'],
    '509': ['knit_v-neck', 'part'],
    '510': ['knotted', 'part'],
    '511': ['kurt', 'shape'],
    '512': ['la', 'style'],
    '513': ['lace', 'fabric'],
    '514': ['lace_layered', 'fabric'],
    '515': ['lace_maxi', 'shape'],
    '516': ['lace_mesh', 'fabric'],
    '517': ['lace_midi', 'shape'],
    '518': ['lace_mini', 'shape'],
    '519': ['lace_overlay', 'fabric'],
    '520': ['lace_panel', 'fabric'],
    '521': ['lace_paneled', 'fabric'],
    '522': ['lace_pencil', 'shape'],
    '523': ['lace_peplum', 'part'],
    '524': ['lace_pleated', 'fabric'],
    '525': ['lace_print', 'fabric'],
    '526': ['lace_sheath', 'shape'],
    '527': ['lace_sheer', 'fabric'],
    '528': ['lace_shift', 'shape'],
    '529': ['lace_skater', 'shape'],
    '530': ['lace_sleeve', 'part'],
    '531': ['lace_trim', 'part'],
    '532': ['lace-paneled', 'fabric'],
    '533': ['lace-trim', 'part'],
    '534': ['lace-trimmed', 'part'],
    '535': ['lace-up', 'part'],
    '536': ['lacy', 'fabric'],
    '537': ['ladder-back', 'part'],
    '538': ['lady', 'style'],
    '539': ['lakers', 'style'],
    '540': ['lapel', 'part'],
    '541': ['laser', 'style'],
    '542': ['lattice', 'fabric'],
    '543': ['layered', 'fabric'],
    '544': ['leaf', 'texture'],
    '545': ['leaf_print', 'texture'],
    '546': ['leather', 'fabric'],
    '547': ['leather_mini', 'shape'],
    '548': ['leather_moto', 'shape'],
    '549': ['leather_paneled', 'fabric'],
    '550': ['leather_pencil', 'shape'],
    '551': ['leather_peplum', 'part'],
    '552': ['leather_quilted', 'fabric'],
    '553': ['leather_skater', 'shape'],
    '554': ['leather_trimmed', 'part'],
    '555': ['leather_varsity', 'shape'],
    '556': ['leather-paneled', 'fabric'],
    '557': ['leather-trimmed', 'part'],
    '558': ['leave', 'texture'],
    '559': ['led', 'fabric'],
    '560': ['leopard', 'texture'],
    '561': ['leopard_print', 'texture'],
    '562': ['life', 'style'],
    '563': ['light', 'style'],
    '564': ['lightning', 'style'],
    '565': ['linen', 'texture'],
    '566': ['linen-blend', 'texture'],
    '567': ['logo', 'style'],
    '568': ['long_sleeve', 'part'],
    '569': ['long-sleeve', 'part'],
    '570': ['long-sleeved', 'part'],
    '571': ['longline', 'shape'],
    '572': ['longline_shirt', 'shape'],
    '573': ['loop', 'fabric'],
    '574': ['loose', 'fabric'],
    '575': ['loose-knit', 'fabric'],
    '576': ['lounge', 'style'],
    '577': ['love', 'style'],
    '578': ['lover', 'style'],
    '579': ['low-rise', 'shape'],
    '580': ['low-rise_skinny', 'shape'],
    '581': ['loyal', 'style'],
    '582': ['luxe', 'style'],
    '583': ['m-slit', 'part'],
    '584': ['m-slit_maxi', 'part'],
    '585': ['mandala', 'texture'],
    '586': ['mandala_print', 'texture'],
    '587': ['mandarin', 'style'],
    '588': ['map', 'style'],
    '589': ['marble', 'texture'],
    '590': ['marble_print', 'texture'],
    '591': ['marilyn', 'style'],
    '592': ['marilyn_monroe', 'style'],
    '593': ['marled', 'texture'],
    '594': ['marled_stripe', 'texture'],
    '595': ['matelot', 'style'],
    '596': ['maxi', 'shape'],
    '597': ['medallion', 'texture'],
    '598': ['medallion_print', 'texture'],
    '599': ['medium', 'shape'],
    '600': ['meow', 'style'],
    '601': ['mesh', 'fabric'],
    '602': ['mesh_overlay', 'fabric'],
    '603': ['mesh_panel', 'fabric'],
    '604': ['mesh_paneled', 'fabric'],
    '605': ['mesh_racerback', 'part'],
    '606': ['mesh-paneled', 'fabric'],
    '607': ['mesh-trimmed', 'part'],
    '608': ['metallic', 'fabric'],
    '609': ['miami', 'style'],
    '610': ['mickey', 'style'],
    '611': ['mickey_mouse', 'style'],
    '612': ['mid_rise', 'shape'],
    '613': ['mid_rise_skinny', 'shape'],
    '614': ['mid-rise', 'shape'],
    '615': ['mid-rise_skinny', 'shape'],
    '616': ['midi', 'shape'],
    '617': ['mina', 'style'],
    '618': ['mineral', 'fabric'],
    '619': ['mineral_wash', 'fabric'],
    '620': ['mini', 'shape'],
    '621': ['minnie', 'style'],
    '622': ['minnie_mouse', 'style'],
    '623': ['mirrored', 'style'],
    '624': ['mixed', 'texture'],
    '625': ['mixed_print', 'texture'],
    '626': ['mixed_stripe', 'texture'],
    '627': ['mob', 'style'],
    '628': ['mock', 'part'],
    '629': ['mock_neck', 'part'],
    '630': ['mock-neck', 'part'],
    '631': ['mod', 'style'],
    '632': ['modernist', 'style'],
    '633': ['monroe', 'style'],
    '634': ['moon', 'style'],
    '635': ['morning', 'style'],
    '636': ['mosaic', 'texture'],
    '637': ['mosaic_print', 'texture'],
    '638': ['moto', 'shape'],
    '639': ['multi-stripe', 'texture'],
    '640': ['muscle', 'shape'],
    '641': ['muse', 'style'],
    '642': ['nautical', 'texture'],
    '643': ['nautical_stripe', 'texture'],
    '644': ['nautical_striped', 'texture'],
    '645': ['neck_ribbed', 'part'],
    '646': ['neck_skater', 'part'],
    '647': ['neck_striped', 'part'],
    '648': ['neckline', 'part'],
    '649': ['neon', 'fabric'],
    '650': ['neoprene', 'fabric'],
    '651': ['nets', 'fabric'],
    '652': ['netted', 'fabric'],
    '653': ['new_york', 'style'],
    '654': ['night', 'style'],
    '655': ['notched_collar', 'part'],
    '656': ['notorious', 'style'],
    '657': ['ny', 'style'],
    '658': ['nyc', 'style'],
    '659': ['nylon', 'fabric'],
    '660': ['off-the-shoulder', 'part'],
    '661': ['oil', 'fabric'],
    '662': ['ombre', 'texture'],
    '663': ['one-button', 'part'],
    '664': ['one-shoulder', 'part'],
    '665': ['open-back', 'part'],
    '666': ['open-front', 'part'],
    '667': ['open-knit', 'part'],
    '668': ['open-shoulder', 'part'],
    '669': ['organza', 'fabric'],
    '670': ['origami', 'fabric'],
    '671': ['ornate', 'texture'],
    '672': ['ornate_paisley', 'texture'],
    '673': ['ornate_print', 'texture'],
    '674': ['overlay', 'fabric'],
    '675': ['overlay_sheath', 'shape'],
    '676': ['oversized', 'shape'],
    '677': ['oxford', 'style'],
    '678': ['paint', 'texture'],
    '679': ['paint_splatter', 'texture'],
    '680': ['painted', 'texture'],
    '681': ['paisley', 'texture'],
    '682': ['paisley_print', 'texture'],
    '683': ['palm', 'texture'],
    '684': ['palm_print', 'texture'],
    '685': ['palm_springs', 'texture'],
    '686': ['palm_tree', 'texture'],
    '687': ['pan', 'style'],
    '688': ['panel', 'fabric'],
    '689': ['paneled', 'fabric'],
    '690': ['paradise', 'style'],
    '691': ['paris', 'style'],
    '692': ['party', 'style'],
    '693': ['patched', 'fabric'],
    '694': ['patchwork', 'fabric'],
    '695': ['pattern', 'texture'],
    '696': ['patterned', 'texture'],
    '697': ['peasant', 'shape'],
    '698': ['pencil', 'shape'],
    '699': ['peplum', 'part'],
    '700': ['perforated', 'fabric'],
    '701': ['performance', 'style'],
    '702': ['pima', 'fabric'],
    '703': ['pin', 'part'],
    '704': ['pineapple', 'style'],
    '705': ['pink', 'style'],
    '706': ['pinstripe', 'texture'],
    '707': ['pinstriped', 'texture'],
    '708': ['pintuck', 'fabric'],
    '709': ['pintuck_pleated', 'fabric'],
    '710': ['pintucked', 'fabric'],
    '711': ['pizza', 'style'],
    '712': ['pj', 'style'],
    '713': ['plaid', 'fabric'],
    '714': ['plaid_shirt', 'fabric'],
    '715': ['please', 'style'],
    '716': ['pleat', 'fabric'],
    '717': ['pleated', 'fabric'],
    '718': ['pleated_skater', 'shape'],
    '719': ['pleated_woven', 'fabric'],
    '720': ['pocket', 'part'],
    '721': ['pointelle', 'fabric'],
    '722': ['polka_dot', 'texture'],
    '723': ['polo', 'shape'],
    '724': ['pom-pom', 'texture'],
    '725': ['ponte', 'fabric'],
    '726': ['popcorn', 'style'],
    '727': ['popover', 'shape'],
    '728': ['posh', 'style'],
    '729': ['power', 'style'],
    '730': ['print', 'texture'],
    '731': ['print_racerback', 'part'],
    '732': ['print_satin', 'fabric'],
    '733': ['print_scuba', 'fabric'],
    '734': ['print_shift', 'shape'],
    '735': ['print_shirt', 'texture'],
    '736': ['print_skater', 'shape'],
    '737': ['print_smock', 'shape'],
    '738': ['print_smocked', 'shape'],
    '739': ['print_strapless', 'part'],
    '740': ['print_strappy', 'part'],
    '741': ['print_surplice', 'part'],
    '742': ['print_tulip', 'shape'],
    '743': ['print_v-neck', 'part'],
    '744': ['print_woven', 'texture'],
    '745': ['printed', 'texture'],
    '746': ['puffer', 'shape'],
    '747': ['pullover', 'shape'],
    '748': ['purl', 'fabric'],
    '749': ['quilted', 'fabric'],
    '750': ['quirky', 'style'],
    '751': ['racerback', 'part'],
    '752': ['rad', 'style'],
    '753': ['raga', 'style'],
    '754': ['raglan', 'part'],
    '755': ['raglan_sleeve', 'part'],
    '756': ['rainbow', 'style'],
    '757': ['raw', 'shape'],
    '758': ['raw-cut', 'shape'],
    '759': ['rebel', 'style'],
    '760': ['red', 'style'],
    '761': ['refined', 'style'],
    '762': ['regime', 'style'],
    '763': ['relaxed', 'style'],
    '764': ['retro', 'style'],
    '765': ['reverse', 'style'],
    '766': ['reversible', 'style'],
    '767': ['rhinestone', 'fabric'],
    '768': ['rib', 'fabric'],
    '769': ['rib-knit', 'fabric'],
    '770': ['ribbed', 'fabric'],
    '771': ['ribbed_stripe', 'texture'],
    '772': ['ribbed-knit', 'fabric'],
    '773': ['ringer', 'texture'],
    '774': ['ripped', 'fabric'],
    '775': ['rise', 'shape'],
    '776': ['rise_skinny', 'shape'],
    '777': ['roll', 'style'],
    '778': ['rolling', 'style'],
    '779': ['rolling_stones', 'style'],
    '780': ['roman', 'style'],
    '781': ['rose', 'style'],
    '782': ['rose_skater', 'shape'],
    '783': ['roses', 'style'],
    '784': ['round', 'shape'],
    '785': ['ruched', 'fabric'],
    '786': ['ruffle', 'fabric'],
    '787': ['ruffle_trim', 'part'],
    '788': ['ruffled', 'fabric'],
    '789': ['rugby', 'style'],
    '790': ['rugby_stripe', 'texture'],
    '791': ['rugby_striped', 'texture'],
    '792': ['run', 'style'],
    '793': ['running', 'style'],
    '794': ['rustic', 'style'],
    '795': ['safari', 'style'],
    '796': ['sateen', 'fabric'],
    '797': ['satin', 'fabric'],
    '798': ['scallop', 'part'],
    '799': ['scalloped', 'part'],
    '800': ['scoop', 'part'],
    '801': ['scoop-neck', 'part'],
    '802': ['scuba', 'fabric'],
    '803': ['scuba_skater', 'shape'],
    '804': ['sea', 'style'],
    '805': ['seam', 'fabric'],
    '806': ['seamless', 'fabric'],
    '807': ['seaside', 'style'],
    '808': ['seersucker', 'fabric'],
    '809': ['self-tie', 'part'],
    '810': ['semi-sheer', 'fabric'],
    '811': ['sequin', 'fabric'],
    '812': ['sequined', 'fabric'],
    '813': ['shaggy', 'fabric'],
    '814': ['shark', 'style'],
    '815': ['shawl', 'part'],
    '816': ['shearling', 'fabric'],
    '817': ['sheath', 'shape'],
    '818': ['sheer', 'fabric'],
    '819': ['sheer-paneled', 'fabric'],
    '820': ['shift', 'shape'],
    '821': ['shirred', 'fabric'],
    '822': ['shirt', 'shape'],
    '823': ['shopping', 'style'],
    '824': ['shore', 'style'],
    '825': ['shoulder', 'part'],
    '826': ['shredded', 'fabric'],
    '827': ['side_slit', 'part'],
    '828': ['side-slit', 'part'],
    '829': ['single-button', 'part'],
    '830': ['skater', 'shape'],
    '831': ['skinny', 'shape'],
    '832': ['skinny_stretch', 'shape'],
    '833': ['skort', 'shape'],
    '834': ['sky', 'style'],
    '835': ['sleek', 'fabric'],
    '836': ['sleeve', 'part'],
    '837': ['sleeveless', 'part'],
    '838': ['slick', 'fabric'],
    '839': ['slim', 'shape'],
    '840': ['slip', 'shape'],
    '841': ['slit', 'part'],
    '842': ['slouchy', 'shape'],
    '843': ['slub', 'fabric'],
    '844': ['slub-knit', 'fabric'],
    '845': ['smart', 'style'],
    '846': ['smile', 'style'],
    '847': ['smock', 'shape'],
    '848': ['smocked', 'shape'],
    '849': ['snap', 'style'],
    '850': ['snoopy', 'style'],
    '851': ['soft', 'style'],
    '852': ['solid', 'style'],
    '853': ['sophisticated', 'texture'],
    '854': ['southwestern', 'texture'],
    '855': ['southwestern-inspired', 'texture'],
    '856': ['southwestern-patterned', 'texture'],
    '857': ['southwestern-print', 'texture'],
    '858': ['sparkling', 'fabric'],
    '859': ['speckled', 'texture'],
    '860': ['spirit', 'style'],
    '861': ['splatter', 'texture'],
    '862': ['split', 'part'],
    '863': ['split-back', 'part'],
    '864': ['split-neck', 'part'],
    '865': ['spongebob', 'style'],
    '866': ['sporty', 'style'],
    '867': ['spotted', 'texture'],
    '868': ['springs', 'style'],
    '869': ['square', 'shape'],
    '870': ['standout', 'style'],
    '871': ['star', 'style'],
    '872': ['stars', 'style'],
    '873': ['stone', 'fabric'],
    '874': ['stone_washed', 'fabric'],
    '875': ['stones', 'fabric'],
    '876': ['straight-leg', 'shape'],
    '877': ['strap', 'part'],
    '878': ['strapless', 'part'],
    '879': ['strapless_tribal', 'part'],
    '880': ['strappy', 'part'],
    '881': ['stretch', 'fabric'],
    '882': ['stretch-knit', 'fabric'],
    '883': ['stripe', 'texture'],
    '884': ['striped', 'texture'],
    '885': ['striped_trapeze', 'shape'],
    '886': ['striped_v-neck', 'part'],
    '887': ['stripes', 'texture'],
    '888': ['structured', 'texture'],
    '889': ['studded', 'fabric'],
    '890': ['studio', 'style'],
    '891': ['suede', 'fabric'],
    '892': ['summer', 'style'],
    '893': ['sun', 'style'],
    '894': ['sunburst', 'style'],
    '895': ['sunflower', 'style'],
    '896': ['surfer', 'style'],
    '897': ['surplice', 'part'],
    '898': ['suspender', 'part'],
    '899': ['sweet', 'style'],
    '900': ['sweetheart', 'style'],
    '901': ['swim', 'style'],
    '902': ['swing', 'shape'],
    '903': ['swiss', 'style'],
    '904': ['t-back', 'part'],
    '905': ['taco', 'style'],
    '906': ['tapestry', 'fabric'],
    '907': ['tartan', 'fabric'],
    '908': ['tasmanian', 'style'],
    '909': ['tassel', 'part'],
    '910': ['tasseled', 'part'],
    '911': ['terry', 'fabric'],
    '912': ['texas', 'style'],
    '913': ['textured', 'fabric'],
    '914': ['textured_woven', 'fabric'],
    '915': ['thermal', 'style'],
    '916': ['tie-back', 'part'],
    '917': ['tie-dye', 'fabric'],
    '918': ['tie-front', 'part'],
    '919': ['tie-neck', 'part'],
    '920': ['tiered', 'fabric'],
    '921': ['tile', 'fabric'],
    '922': ['toggle', 'part'],
    '923': ['tokyo', 'style'],
    '924': ['tonal', 'texture'],
    '925': ['topstitched', 'part'],
    '926': ['tower', 'style'],
    '927': ['track', 'style'],
    '928': ['training', 'style'],
    '929': ['trapeze', 'shape'],
    '930': ['tree', 'style'],
    '931': ['trench', 'style'],
    '932': ['triangle', 'style'],
    '933': ['tribal', 'texture'],
    '934': ['tribal-inspired', 'texture'],
    '935': ['trim', 'part'],
    '936': ['trimmed', 'part'],
    '937': ['tropical', 'style'],
    '938': ['trouble', 'style'],
    '939': ['trouser', 'shape'],
    '940': ['tube', 'shape'],
    '941': ['tulip', 'shape'],
    '942': ['tulip-back', 'part'],
    '943': ['tulle', 'fabric'],
    '944': ['tunic', 'shape'],
    '945': ['tupac', 'style'],
    '946': ['turtle-neck', 'part'],
    '947': ['tweed', 'fabric'],
    '948': ['twill', 'fabric'],
    '949': ['twist-front', 'part'],
    '950': ['twisted', 'part'],
    '951': ['two-button', 'part'],
    '952': ['two-tone', 'texture'],
    '953': ['utility', 'style'],
    '954': ['v-back', 'part'],
    '955': ['v-cut', 'part'],
    '956': ['v-neck', 'part'],
    '957': ['van', 'style'],
    '958': ['varsity', 'style'],
    '959': ['varsity-striped', 'texture'],
    '960': ['velvet', 'fabric'],
    '961': ['velveteen', 'fabric'],
    '962': ['venice', 'style'],
    '963': ['vent', 'part'],
    '964': ['vented_hem', 'part'],
    '965': ['vertical', 'shape'],
    '966': ['voyager', 'style'],
    '967': ['waffle', 'fabric'],
    '968': ['wake', 'style'],
    '969': ['wash', 'fabric'],
    '970': ['washed', 'fabric'],
    '971': ['watercolor', 'texture'],
    '972': ['wave', 'style'],
    '973': ['weekend', 'style'],
    '974': ['west', 'style'],
    '975': ['wide-leg', 'shape'],
    '976': ['wifey', 'style'],
    '977': ['wild', 'style'],
    '978': ['wildflower', 'style'],
    '979': ['windbreaker', 'shape'],
    '980': ['windowpane', 'shape'],
    '981': ['woke', 'style'],
    '982': ['workout', 'style'],
    '983': ['woven', 'fabric'],
    '984': ['wrap', 'shape'],
    '985': ['y-back', 'part'],
    '986': ['yoga', 'style'],
    '987': ['yoke', 'style'],
    '988': ['york', 'style'],
    '989': ['youth', 'style'],
    '990': ['zeppelin', 'style'],
    '991': ['zig', 'texture'],
    '992': ['zigzag', 'texture'],
    '993': ['zip', 'part'],
    '994': ['zip-front', 'part'],
    '995': ['zip-pocket', 'part'],
    '996': ['zip-up', 'part'],
    '997': ['zipped', 'part'],
    '998': ['zipper', 'part'],
    '999': ['zippered', 'part']
}

