- hosts: braini-paperdoll
  gather_facts: no
  tasks:
  - name: git pull braini pd
    git: repo=git@bitbucket.org:trendiGuru/core.git dest=/home/pd_user/trendi accept_hostkey=yes
    sudo_user: jeremy

- hosts: braini-nonpaperdoll
  gather_facts: no
  tasks:
  - name: git pull nonpd
    git: repo=git@bitbucket.org:trendiGuru/core.git dest=/home/jeremy/trendi accept_hostkey=yes
    sudo_user: jeremy

- hosts: gcloud-dev
  gather_facts: no
  tasks:
  - name: git pull gclouddev
    git: repo=git@bitbucket.org:trendiGuru/core.git dest=/home/developer/python-packages/trendi accept_hostkey=yes
    sudo_user: jeremy


# Flush only one db in a redis instance
#- redis: command=flush db=1 flush_mode=db
#mongostat
#redis-cli ping