- hosts: braini-paperdoll
  gather_facts: no
  tasks:

  - name: ping
  - ping:

  - name: print to stdout
    command: echo "hello"
    register: hello

  - debug: msg="{{ hello.stdout }}"
  - debug: msg="{{ hello.stderr }}"

#- hosts: braini-nonpaperdoll

# Flush only one db in a redis instance
#- redis: command=flush db=1 flush_mode=db
#mongostat
#redis-cli ping