#https://github.com/RenderToolbox3/VirtualScenes/wiki/Matlab-on-Docker-and-EC2
#check this for gui https://hub.docker.com/r/sinclab/webdemo-base-matlab/
# sshd, matlab, dcmdump (via dcmtk)

FROM ubuntu:14.04

ADD matlab.txt /mcr-install/matlab.txt
ADD id_rsa.pub /root/.ssh/authorized_keys
ADD assets /root/assets


RUN \
   apt-get update && \
   apt-get install -y curl wget xorg unzip openssh-server dcmtk && \
   mkdir /var/run/sshd

RUN \
   cd /mcr-install && \

#this dockerfile originally got the installer with a wget
#   wget -nv http://www.mathworks.de/supportfiles/downloads/R2013b/deployment_files/R2013b/installers/glnxa64/MCR_R2013b_glnxa64_installer.zip && \

 http://esd.mathworks.com/matlab_R2015a_glnxa64.zip

#for license manager
RUN apt-get install -y lsb

#but since i can't find the actual remote file I add it locally - requiring the docker user to download it :<<

ADD /home/jeremy/Downloads/matlab_R2015a_glnxa64.zip /matlab_R2015a_glnxa64.zip

RUN unzip matlab_R2015a_glnxa64.zip
RUN mkdir /opt/mcr && \
RUN   ./install -inputFile matlab.txt
RUN   cd /
RUN   rm -rf mcr-install

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]



#./install
#cd Matlab_PATH/bin
#./activate_matlab.sh
#alias matlab=Matlab_PATH/bin/matlab

#installation key for extremeli :
#38614-20740-50551-13491-24782-10169-30466-19304-14029-23772-24554-35060-16454-14177-36777-61237-03922-49904-57728-41534

#to run gui app (giving up since i can't seem to install license manager - product not given as an option in install....)
#FROM ubuntu:14.04

#RUN apt-get update && apt-get install -y firefox

# Replace 1000 with your user / group id
#RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

#USER developer
#ENV HOME /home/developer
#CMD /usr/bin/firefox


#somethign to try - just link -v to matlab files and run install 