FROM httpd:2.4
COPY ./public-html/ /usr/local/apache2/htdocs/

#Then, run the commands to build and run the Docker image:
#$ docker build -t my-apache2 .
#$ docker run -it --rm --name my-running-app my-apache2